### PR TITLE
use salt['pillar.get'] to avoid  bogus entries. Fixes #26

### LINKED ISSUE #26: Domain customization generates bogus entry
Hello,

I'm a relatively new user of Salt and I've been working on a project that involves using this formula.
However, it would seem that the relatively recent `domain` part of the formula is not working properly in my environment:

OS: CentOS 7
Saltstack: ``2016.11.8`` with salt-ssh.

Indeed, it generates entries such as this one:
```
192.168.122.53     saltmaster saltmaster.<function caller at 0x7f4993c70aa0>
```
As you can see, it doesn't seem to be able to actually grab the domain and instead prints a reference to a function, which changes every run.

I've been trying to tinker a bit with the code and replacing `salt.pillar.get` with `salt['pillar.get']` in https://github.com/saltstack-formulas/hostsfile-formula/blob/master/hostsfile/init.sls#L23 seems to do the trick.

If this workaround sounds reasonable I'll go ahead and open a PR with that modification but I am not familiar with best practices when it comes to making formulas so I'd rather get your input on that issue.

### PR DESCRIPTION
**Pull request by wonko21**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [x] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Fixes #26.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Thanks for providing this, @wonko21.  This will fail the `commitlint` check due to our commit message formatting requirements (see the [contributing guidelines](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst)), but I can fix that upon merging this PR once the rest of the tests complete.

**Comment by wonko21** [comment]
Sorry about the commitlint. I only saw the guidlines after the fact.

**Comment by myii** [comment]
@wonko21 Not a problem, thanks for the fix!

**Comment by myii** [comment]
@wonko21 Merged, with the fixed commit message (as you can see when this reaches the release notes and changelog).

**Pull request merged**
