### PR TITLE
Fixed formula so that if the mine function returns a single IP as a s…

### PR DESCRIPTION
**Pull request by bentwire**
…tring, it does not get corrupted.

### CODE REVIEW

**Comment by bentwire** [comment]
If we want to pull mine out of this and move it to pillar I could write up a patch for that instead.

**Comment by iggy** [comment]
Mine lookups in pillar are still kind of iffy... let's just go with this for now.

**Comment by bentwire** [comment]
@iggy Would you mind if I created a branch with the pillarization changes in it and give you a PR for that?  You could create a separate branch for it here if you would like.

**Comment by iggy** [comment]
The problem is there are too many versions of Salt in the wild where mine lookups in pillar just don't work.

**Comment by bentwire** [comment]
@iggy Ah, yeah I see the issue there...

**Pull request merged**
